'use client';

import { useState, useEffect } from 'react';
import { useAuth } from '@smileguard/shared-hooks';
import { bookSlot, getAllBlockedSlots, isSlotTaken, getPatientAppointments } from '@/lib/appointmentService';
import type { Appointment } from '@/lib/database';

const SERVICES = [
  { id: 'cleaning', name: 'Cleaning', duration: 30, price: 1500 },
  { id: 'whitening', name: 'Whitening', duration: 60, price: 5000 },
  { id: 'fillings', name: 'Fillings', duration: 45, price: 2000 },
  { id: 'root-canal', name: 'Root Canal', duration: 90, price: 8000 },
  { id: 'extraction', name: 'Extraction', duration: 30, price: 1500 },
  { id: 'braces', name: 'Braces Consultation', duration: 60, price: 35000 },
  { id: 'implants', name: 'Implants Consultation', duration: 60, price: 45000 },
  { id: 'xray', name: 'X-Ray', duration: 15, price: 500 },
  { id: 'checkup', name: 'Check-up', duration: 20, price: 300 },
];

const TIME_SLOTS = [
  '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
  '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30',
];

interface BookAppointmentProps {
  onSuccess?: (appointment: Appointment) => void;
  onCancel?: () => void;
}

export default function BookAppointment({ onSuccess, onCancel }: BookAppointmentProps) {
  const { currentUser } = useAuth();
  const [selectedService, setSelectedService] = useState<(typeof SERVICES)[0] | null>(null);
  const [selectedDate, setSelectedDate] = useState<string>('');
  const [selectedTime, setSelectedTime] = useState<string>('');
  const [notes, setNotes] = useState<string>('');
  const [isBooking, setIsBooking] = useState(false);
  const [blockedSlots, setBlockedSlots] = useState<any[]>([]);
  const [loadingBlockedSlots, setLoadingBlockedSlots] = useState(true);
  const [fullyBookedDates, setFullyBookedDates] = useState<Set<string>>(new Set());
  const [userAppointments, setUserAppointments] = useState<Appointment[]>([]);
  const [loadingUserData, setLoadingUserData] = useState(true);

  useEffect(() => {
    fetchAllBlockedSlots();
  }, []);

  useEffect(() => {
    if (!currentUser) return;

    async function fetchUserAppointments() {
      setLoadingUserData(true);
      try {
        if (!currentUser) return;
        const appointments = await getPatientAppointments(currentUser.id);
        setUserAppointments(appointments);
      } catch (err) {
        console.error('Error fetching user appointments:', err);
      } finally {
        setLoadingUserData(false);
      }
    }

    fetchUserAppointments();
  }, [currentUser]);

  const fetchAllBlockedSlots = async () => {
    setLoadingBlockedSlots(true);
    try {
      const slots = await getAllBlockedSlots();
      setBlockedSlots(slots);

      const dateCounts: Record<string, number> = {};
      for (const slot of slots) {
        dateCounts[slot.date] = (dateCounts[slot.date] ?? 0) + 1;
      }

      const full = new Set(
        Object.entries(dateCounts)
          .filter(([, count]) => count >= TIME_SLOTS.length)
          .map(([date]) => date)
      );

      setFullyBookedDates(full);
    } catch (error) {
      console.error('Error fetching blocked slots:', error);
      setBlockedSlots([]);
    } finally {
      setLoadingBlockedSlots(false);
    }
  };

  const isSlotDisabled = (date: string, time: string) => {
    return isSlotTaken(blockedSlots, date, time);
  };

  const handleBooking = async () => {
    if (!selectedService || !selectedDate || !selectedTime || !currentUser) {
      alert('Please select service, date, and time');
      return;
    }

    setIsBooking(true);
    try {
      const result = await bookSlot(
        currentUser.id,
        '', // dentistId (optional for now)
        selectedService.name,
        selectedDate,
        selectedTime
      );

      if (result.success) {
        alert('Appointment booked successfully!');
        if (onSuccess) {
          onSuccess({
            id: '1', // This will be generated by Supabase
            patient_id: currentUser.id,
            dentist_id: null,
            service: selectedService.name,
            appointment_date: selectedDate,
            appointment_time: selectedTime,
            notes: notes || '',
            status: 'scheduled',
            created_at: new Date().toISOString(),
          });
        }
        setSelectedService(null);
        setSelectedDate('');
        setSelectedTime('');
        setNotes('');
      }
    } catch (error) {
      console.error('Error booking appointment:', error);
      alert('Failed to book appointment');
    } finally {
      setIsBooking(false);
    }
  };

  if (loadingBlockedSlots) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <h1 className="text-4xl font-bold text-gray-800 mb-2">📅 Book an Appointment</h1>
      <p className="text-gray-600 mb-8">Schedule a visit with our dental professionals</p>

      {/* Upcoming Appointments Summary */}
      {!loadingUserData && userAppointments.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
          <div className="bg-green-50 rounded-lg shadow-md p-6 border-l-4 border-green-600">
            <p className="text-sm text-gray-600">Upcoming Appointments</p>
            <p className="text-3xl font-bold text-green-700">{userAppointments.length}</p>
            <p className="text-xs text-gray-500 mt-2">Already scheduled</p>
          </div>
          <div className="bg-blue-50 rounded-lg shadow-md p-6 border-l-4 border-blue-600">
            <p className="text-sm text-gray-600">Next Available</p>
            <p className="text-3xl font-bold text-blue-700">{TIME_SLOTS.length} slots</p>
            <p className="text-xs text-gray-500 mt-2">Per day</p>
          </div>
        </div>
      )}

      {/* Booking Form */}
      <div className="bg-white rounded-lg shadow-md p-6 mb-8">
        {/* Service Selection */}
        <div className="mb-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Step 1: Select Service</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {SERVICES.map((service) => (
              <button
                key={service.id}
                onClick={() => setSelectedService(service)}
                className={`p-4 rounded-lg border-2 text-left transition ${
                  selectedService?.id === service.id
                    ? 'border-blue-600 bg-blue-50 shadow-md'
                    : 'border-gray-200 hover:border-blue-300 hover:shadow'
                }`}
              >
                <div className="font-semibold text-gray-800">{service.name}</div>
                <div className="text-sm text-gray-600 mt-1">{service.duration} mins</div>
                <div className="text-blue-600 font-bold mt-2">₱{service.price}</div>
              </button>
            ))}
          </div>
        </div>

        <hr className="my-8" />

        {/* Date Selection */}
        <div className="mb-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Step 2: Select Date</h2>
          <input
            type="date"
            value={selectedDate}
            onChange={(e) => setSelectedDate(e.target.value)}
            disabled={fullyBookedDates.has(selectedDate)}
            className="w-full md:w-1/3 p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600"
          />
          {fullyBookedDates.has(selectedDate) && (
            <p className="text-sm text-red-600 mt-2">⚠️ This date is fully booked</p>
          )}
        </div>

        <hr className="my-8" />

        {/* Time Selection */}
        <div className="mb-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Step 3: Select Time</h2>
          <div className="grid grid-cols-3 md:grid-cols-7 gap-2">
            {TIME_SLOTS.map((time) => (
              <button
                key={time}
                onClick={() => setSelectedTime(time)}
                disabled={isSlotDisabled(selectedDate, time)}
                className={`p-2 rounded-lg text-sm font-medium transition ${
                  selectedTime === time
                    ? 'bg-blue-600 text-white shadow-md'
                    : isSlotDisabled(selectedDate, time)
                      ? 'bg-gray-200 text-gray-400 cursor-not-allowed'
                      : 'bg-gray-100 hover:bg-blue-100 hover:border-blue-300'
                }`}
              >
                {time}
              </button>
            ))}
          </div>
        </div>

        <hr className="my-8" />

        {/* Notes */}
        <div className="mb-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Step 4: Additional Notes (Optional)</h2>
          <textarea
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Any special requests, medical concerns, or conditions we should know about..."
            className="w-full p-4 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600 bg-gray-50"
            rows={4}
          />
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-col md:flex-row gap-4">
        <button
          onClick={handleBooking}
          disabled={isBooking || !selectedService || !selectedDate || !selectedTime}
          className="flex-1 p-4 bg-blue-600 text-white font-bold rounded-lg hover:bg-blue-700 disabled:bg-gray-400 transition text-lg"
        >
          {isBooking ? '⏳ Booking...' : '✓ Confirm Appointment'}
        </button>
        {onCancel && (
          <button
            onClick={onCancel}
            className="flex-1 p-4 bg-gray-300 text-gray-800 font-semibold rounded-lg hover:bg-gray-400 transition"
          >
            Cancel
          </button>
        )}
      </div>
    </div>
  );
}
